### ISSUE TITLE
Gleam modules are not compiled to beam when using gleam v0.25.0

### ISSUE THREAD

**Issue by silicium14** [gleam-lang/mix_gleam#26]
When using gleam v0.25.0 the erlang code generated by gleam is not compiled later in the compilation stages when using mix tasks. As a result gleam modules are not available at runtime. I suspect it is caused by the change of output directory for the erlang code produced by gleam https://github.com/gleam-lang/gleam/commit/b35ecd3c58b9ca4448392837c4ffe70c877d0b57#diff-bab1783d97666c826f55924d7d1dc3f73c005ddd445b14c77ce2e52880fcdb64R5.

Changing `:erlc_paths` in `mix.exs` to `["build/dev/erlang/#{@app}/_gleam_artefacts"]` works as a fix for modules of current application but the dependencies are still not available.

**Comment by lpil** [comment]
Thanks for the report! Let's get this fixed
