### ISSUE TITLE
`mix compile` fails to compile if importing a gleam package using a local path or a git url

### ISSUE THREAD

**Issue by ishmam-mahmud** [gleam-lang/mix_gleam#31]
When the gleam dependency is imported using a git url, rather that with a version number(and thus downloaded from hex.pm), the `mix compile` command fails with the following error

```
==> some_package
Compiling 10 files (.gleam)
error: Unknown module
  ┌─ ./test/some_package_test.gleam:1:8
  │
1 │ import gleeunit
  │        ^^^^^^^^

No module has been found with the name `gleeunit`.
could not compile dependency :some_package, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile some_package", update it with "mix deps.update some_package" or clean it with "mix deps.clean some_package"
** (MixGleam) Compilation failed
```

`gleeunit` is a dev dependency of the package I'm trying to use.

The same error happens if I import the package locally using a file path instead of a git server url.

If I delete the test folder locally, then there is no error and `mix compile` succeeds.

**Comment by lpil** [comment]
Thanks for the report @ishmam-mahmud !

@gleam-lang/elixir-team is this something we expect to work currently?

**Comment by tynanbe** [comment]
That was indeed untested behavior; however, I just tried changing this dep in the `basic_project` test project from this repository, and it worked as expected :shrug:

```elixir
{:gleam_stdlib, git: "https://github.com/gleam-lang/stdlib.git", override: true}
```

**Comment by tynanbe** [comment]
Closing this issue as resolved. Please feel free to open a new one if you experience any further trouble.
