### ISSUE TITLE
Elixir 1.15 support

### ISSUE THREAD

**Issue by Hentioe** [gleam-lang/mix_gleam#34]
Prerequisite: I have installed the latest version (0.6.1) of `mix_gleam`.

My `.tool-versions`:

```
erlang 26.0.2
elixir 1.15.4-otp-26
```

Run `mix test`:

```
** (Mix) The task "compile.gleam" could not be found. Did you mean "compile.erlang"?
```

When I change the Elixir version to `1.14.5-otp-26`, everything works fine, including the function calling `gleam_stdlib` in IEx.

**Comment by lpil** [comment]
Tagging @gleam-lang/elixir-team 🙏

**Comment by Hentioe** [comment]
@lpil I found that in the Elixir 1.15 environment, after using `mix archive.install hex mix_gleam`, adding `mix_gleam` to the deps, and running `mix deps.get`, it is possible to compile Gleam code and libraries normally in the 1.15 environment. For `1.14`, there is no need to add `mix_gleam` as a dependency.

**Comment by tynanbe** [comment]
@Hentioe, please see try adding `prune_code_paths: false` to your `mix.exs` and doing a clean build.

**Comment by Hentioe** [comment]
@tynanbe In the Elixir `1.16.0-rc.0` environment, install the latest version of mix_gleam (`0.6.2`), add the `prune_code_paths: false` configuration, use `mix_gleam` perfectly without needing to add it to deps, thanks for your contribution!
