### ISSUE TITLE
Elixir-ls infinite compile loop

### ISSUE THREAD

**Issue by simonprev** [gleam-lang/mix_gleam#5]
After integrating Gleam in an Elixir codebase, I found that elixir-ls never stops to compile the project. It can be easily reproduced with https://github.com/midas-framework/elixir_with_gleam.

## Setup:

```
elixir 1.11.3-otp-23
erlang 23.1.1
gleam 0.9.0
```

But I also tested it with different permutations of Gleam 0.13.2, Erlang 22 and Elixir 1.10 with the same result.

1. Clone the repository
2. Open an editor with elixir-ls running (like VSCode)
3. See in the output that the project is compiled immediately after it finish to compile

It may be a side effect that every Gleam file is recompiled when starting a mix project (the stdlib included). Executing `mix compile` 2 times in a row without modification triggers a full compile of the Elixir project.

https://user-images.githubusercontent.com/464900/114459112-1abada00-9bae-11eb-85a1-c1642140203c.mp4

**Comment by lpil** [comment]
Aye, see this issue here: https://github.com/gleam-lang/mix_gleam/issues/2

This plugin may be reworked in the near future so this will no longer be a problem.
